---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.name }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName }}
  enableSuperuserAccess: {{ .Values.enableSuperuserAccess }}
  superuserSecret: {{ .Values.superuserSecret }}
  primaryUpdateStrategy: {{ .Values.primaryUpdateStrategy }}
  {{- with .Values.backup }}
  backup:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.externalClusters }}
  externalClusters:
    {{- range $reg, $props := .Values.externalClusters }}
    - name: {{ $props.name }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enablePodMonitor }}
  {{- with .Values.postgresql }}
  postgresql:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storage:
    size: {{ .Values.storage.size }}
  bootstrap:
    {{- if .Values.bootstrap.initdb }}
    {{- with .Values.bootstrap.initdb }}
    initdb:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if .Values.bootstrap.recovery }}
    {{- with .Values.bootstrap.recovery }}
    recovery:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- if or .Values.certificates.server.enabled .Values.certificates.client.enabled }}
  certificates:
  {{- if and .Values.certificates.server.enabled }}
  {{- if .Values.certificates.server.generate }}
    serverTLSSecret: "{{ .Values.name }}-server-cert"
    serverCASecret: "{{ .Values.name }}-server-ca-key-pair"
  {{ else }}
    serverTLSSecret: {{ .Values.certificates.server.serverTLSSecret }}
    serverCASecret: {{ .Values.certificates.server.serverCASecret }}
  {{- end }}
  {{- end }}
  {{- if and .Values.certificates.client.enabled }}
  {{- if .Values.certificates.client.generate }}
    clientCASecret: "{{ .Values.name }}-client-ca-key-pair"
    replicationTLSSecret: "{{ .Values.name }}-client-cert"
  {{ else }}
    clientCASecret: {{ .Values.certificates.client.clientCASecret }}
    replicationTLSSecret: {{ .Values.certificates.client.replicationTLSSecret }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.managed.roles }}
  managed:
    roles:
    {{- range $reg, $props := .Values.managed.roles }}
    - name: {{ $props.name }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
