name: "cnpg"

instances: 3

superuserSecret:
  name: superuser-secret

bootstrap:
  initdb:
    # -- initial database to create
    database: app
    # -- owner of the initial database that is created above
    owner: app
    secret:
      name: app-secret
    # -- list of SQL commands to run as part of the init scripts
    postInitSQL:
      - CREATE ROLE friend

backup:
  retentionPolicy: "30d"
  barmanObjectStore:
    destinationPath: "backups"
    # -- how long to keep backups for
    s3Credentials:
      accessKeyId:
        name: "aws-creds"
        key : "ACCESS_KEY_ID"
      secretAccessKey:
        name: "aws-creds"
        key : "ACCESS_SECRET_KEY"


scheduledBackup:
  name: example-backup
  spec:
    schedule: "0 0 0 * * *" 
    backupOwnerReference: self
    cluster:
      name: pg-backup

monitoring:
  enablePodMonitor: true

postgresql:
  pg_hba:
    - hostnossl all all 0.0.0.0/0 reject
    - hostssl all all 0.0.0.0/0 cert clientcert=verify-full

storage:
  size: 1Gi
