name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          #if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          #fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: verify cluster and local path
        run: |
          kubectl config set-context kind-chart-testing
          kubectl cluster-info
          kubectl get pods -A
          pwd
          ls -hal
          
      - name: Install Certmanager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set installCRDs=true \
            --set prometheus.enabled=false
            
      - name: Install CNPG Operator
        run: |
          helm repo add cnpg-operator https://cloudnative-pg.github.io/charts
          helm repo update
          helm install cnpg-operator cnpg-operator/cloudnative-pg \
            --namespace cnpg-system \
            --create-namespace

      - name: Creat testing values
        run: |
          cat << EOF > values.yaml
          name: "cnpg"
          instances: 1
          superuserSecret:
            name: null
          bootstrap:
            initdb:
              database: app
              owner: app
              secret:
                name: null
          certificates:
            server:
              enabled: true
              generate: true
              serverTLSSecret: ""
              serverCASecret: ""
            client:
              enabled: true
              generate: true
              clientCASecret: ""
              replicationTLSSecret: ""
            user:
              enabled: true
              username: "app"
          monitoring:
            enablePodMonitor: false
          postgresql:
            pg_hba:
              - hostnossl all all 0.0.0.0/0 reject
              - hostssl all all 0.0.0.0/0 cert clientcert=verify-full
          storage:
            size: 1Gi
          testApp:
            enabled: true
          EOF
            
      - name: Install CNPG cluster
        run: |
          #helm repo add cnpg-cluster https://small-hack.github.io/cloudnative-pg-tenant-chart
          #helm repo update
          #helm install cnpg-cluster cnpg-cluster/cnpg-cluster --values values.yaml
          helm template . -f values.yaml > deploy.yaml
          cat deploy.yaml
          
      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
