name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          #if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          #fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add dependency helm chart repos and install
        run: |
          helm repo add cnpg-operator https://cloudnative-pg.github.io/charts
          helm repo add jetstack https://charts.jetstack.io
          helm repo add cnpg-cluster https://small-hack.github.io/cloudnative-pg-tenant-chart
          helm repo update
          helm install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set installCRDs=true \
            --set prometheus.enabled=false
          helm install cnpg-operator cnpg-operator/cloudnative-pg \
            --namespace cnpg-system \
            --create-namespace cnpg-operator/cloudnative-pg \
            --wait
          helm install cnpg-cluster cnpg-cluster/cnpg-cluster \
            --set instances=1 \
            --set bootstrap.initdb.secret.name=null \
            --set backup=null \
            --set scheduledBackup=null \
            --set certificate.server.enabled=true \
            --set certificate.server.generate=true \
            --set certificate.client.enabled=true \
            --set certificate.client.enabled=true \
            --set certificate.user.enabled=true \
            --set testApp.enabled=true
          
      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
