---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-client-cert"
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.name }}-client-cert"
spec:
  secretName: "{{ .Values.name }}-client-cert"
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: "{{ .Values.name }}-selfsigned-issuer"
    kind: Issuer
    group: cert-manager.io
