---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Values.name }}-selfsigned-issuer"
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-server-secret"
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.name }}-server-cert"
spec:
  secretName: "{{ .Values.name }}-server-cert"
  usages:
    - server auth
  dnsNames:
    - "{{ .Values.name }}-lb.internal.mydomain.net"
    - "{{ .Values.name }}-rw"
    - "{{ .Values.name }}-rw.default"
    - "{{ .Values.name }}-rw.default.svc"
    - "{{ .Values.name }}-r"
    - "{{ .Values.name }}-r.default"
    - "{{ .Values.name }}-r.default.svc"
    - "{{ .Values.name }}-ro"
    - "{{ .Values.name }}-ro.default"
    - "{{ .Values.name }}-ro.default.svc"
  issuerRef:
    name: "{{ .Values.name }}-selfsigned-issuer"
    kind: Issuer
    group: cert-manager.io

