---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: {{ .Values.instances}}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.destinationPath }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.backup.s3Credentials.accessKeyId.name }}
          key: {{ .Values.backup.s3Credentials.accessKeyId.key }}
        secretAccessKey:
          name: {{ .Values.backup.s3Credentials.secretAccessKey.name }}
          key: {{ .Values.backup.s3Credentials.secretAccessKey.key }}
    retentionPolicy: {{ .Values.backup.retentionPolicy }}
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enablePodMonitor }}
  {{- with .Values.postgresql }}
  postgresql:
    {{- toYaml . | nindent 4}}
  {{- end }}
  storage:
    size: {{ .Values.storage.size }}
  {{- with .Values.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.scheduledBackup.name }}
spec:
  schedule: {{ .Values.scheduledBackup.spec.schedule }}
  backupOwnerReference: {{ .Values.scheduledBackup.spec.backupOwnerReference }} 
  cluster:
    name: {{ .Values.scheduledBackup.spec.cluster.name }}
