---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.name }}
spec:
  instances: {{ .Values.instances}}
  certificates:
    clientCASecret: "{{ .Values.name}}-client-cert"
    replicationTLSSecret: "{{ .Values.name }}-client-cert"
  {{- with .Values.backup }}
  backup:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enablePodMonitor }}
  {{- with .Values.postgresql }}
  postgresql:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storage:
    size: {{ .Values.storage.size }}
  {{- with .Values.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificates }}
  certificates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
